name: Verify for TE

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# This is what will cancel the workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[docker_verify]')"
    steps:
    - uses: actions/checkout@v2
    - name: Verify tfb
      run: |
        git clone https://github.com/TechEmpower/FrameworkBenchmarks
        cd docker/techempower-config/
        cp -rf benchmark_config.json postgresql base/*.dockerfile lang/*.dockerfile scripts/*.sh *.sh *.dockerfile ../../FrameworkBenchmarks/frameworks/C++/ffead-cpp/
        cd ../../FrameworkBenchmarks
        ./tfb --mode verify --test-dir C++/ffead-cpp
